# name: Metrics
# on:
#   # Schedule daily updates
#   schedule: [{cron: "0 0 * * *"}]
#   # (optional) Run workflow manually
#   workflow_dispatch:
#   # (optional) Run workflow when pushing on master/main
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           token: ${{ secrets.METRICS_TOKEN }}

name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"